use_frameworks!

target 'AudioKitAudioIO_Example' do
  pod 'AudioKitAudioIO', :path => '../'

  target 'AudioKitAudioIO_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 1.2.0'
    pod 'Nimble', '~> 7.0.2'
  end
end
